# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: digital_scale.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64igital_scale.proto\x12\rdigital_scale\"4\n\x05Image\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"2\n\nImageArray\x12$\n\x06images\x18\x01 \x03(\x0b\x32\x14.digital_scale.ImageBI\n\x16\x63h.claid.digital_scaleB\x15\x44igitalScaleDataTypesP\x01Z\x16\x63h.claid/digital_scaleb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digital_scale_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026ch.claid.digital_scaleB\025DigitalScaleDataTypesP\001Z\026ch.claid/digital_scale'
  _IMAGE._serialized_start=38
  _IMAGE._serialized_end=90
  _IMAGEARRAY._serialized_start=92
  _IMAGEARRAY._serialized_end=142
# @@protoc_insertion_point(module_scope)
